name: Node.js CI

on:
  push:
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - run: CI=false npm run build-all
            - name: Start Node.js server
              run: |
                  npm run start-production &
                  sleep 5
                  curl http://localhost:4000 || exit 1
            - name: Kill Node.js server
              run: |
                  kill $(lsof -t -i:4000)
              if: always()

